/**
 * List prices of the AI models AIC can recommend between, per million tokens,
 * in US dollars, standard (not batch) rate, short-context tier.
 *
 * Generated from the providers' own pricing and deprecation pages on the date
 * below, and checked by hand. Prices change: refresh this file at least every
 * quarter (scripts are not involved; edit it and update AS_OF). A null price
 * means the provider no longer lists one.
 */
export type ModelTier = 'frontier' | 'mid' | 'small';
export type ModelStatus = 'active' | 'deprecated' | 'retired';
export type ModelPrice = {
  provider: 'openai' | 'anthropic' | 'google' | 'mistral';
  id: string;
  aliases: string[];
  tier: ModelTier;
  inputPerM: number | null;
  outputPerM: number | null;
  status: ModelStatus;
  /** The day the provider stops serving it, where announced. */
  endsOn: string | null;
  /** The provider's named replacement, where it names one. */
  replacement: string | null;
  /** A promotional price, and the list price it returns to afterwards. */
  promo: { until: string; inputPerM: number; outputPerM: number } | null;
};

export const PRICES_AS_OF = '2026-10-05';

export const PRICE_SOURCES: { provider: string; url: string }[] = [
  {
    provider: 'openai',
    url: 'https://developers.openai.com/api/docs/pricing',
  },
  {
    provider: 'openai',
    url: 'https://developers.openai.com/api/docs/deprecations',
  },
  {
    provider: 'anthropic',
    url: 'https://platform.claude.com/docs/en/about-claude/pricing',
  },
  {
    provider: 'anthropic',
    url: 'https://platform.claude.com/docs/en/about-claude/model-deprecations',
  },
  {
    provider: 'anthropic',
    url: 'https://platform.claude.com/docs/en/about-claude/models/overview',
  },
  {
    provider: 'google',
    url: 'https://ai.google.dev/gemini-api/docs/pricing',
  },
  {
    provider: 'google',
    url: 'https://ai.google.dev/gemini-api/docs/deprecations',
  },
  {
    provider: 'mistral',
    url: 'https://docs.mistral.ai/inference/pricing',
  },
  {
    provider: 'mistral',
    url: 'https://docs.mistral.ai/getting-started/models/models_overview/',
  },
];

export const MODEL_PRICES: ModelPrice[] = [
  { provider: 'openai', id: 'gpt-6-astra', aliases: [], tier: 'frontier', inputPerM: 10, outputPerM: 50, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-6.1-sol', aliases: [], tier: 'mid', inputPerM: 2, outputPerM: 10, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-6-sol', aliases: [], tier: 'mid', inputPerM: 2, outputPerM: 10, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-6-luna', aliases: [], tier: 'small', inputPerM: 0.1, outputPerM: 0.5, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.6-sol', aliases: [], tier: 'frontier', inputPerM: 4, outputPerM: 20, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.6-terra', aliases: [], tier: 'mid', inputPerM: 2, outputPerM: 12, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.6-luna', aliases: [], tier: 'small', inputPerM: 0.2, outputPerM: 1.2, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.5', aliases: [], tier: 'frontier', inputPerM: 5, outputPerM: 30, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.5-pro', aliases: [], tier: 'frontier', inputPerM: 30, outputPerM: 180, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.4', aliases: [], tier: 'frontier', inputPerM: 2.5, outputPerM: 15, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.4-mini', aliases: [], tier: 'mid', inputPerM: 0.75, outputPerM: 4.5, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.4-nano', aliases: [], tier: 'small', inputPerM: 0.2, outputPerM: 1.25, status: 'deprecated', endsOn: '2027-04-01', replacement: 'gpt-6-luna', promo: null },
  { provider: 'openai', id: 'gpt-5.4-pro', aliases: [], tier: 'frontier', inputPerM: 30, outputPerM: 180, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.3-codex', aliases: [], tier: 'mid', inputPerM: 1.75, outputPerM: 14, status: 'deprecated', endsOn: '2027-04-01', replacement: 'gpt-6-sol', promo: null },
  { provider: 'openai', id: 'gpt-5.2', aliases: [], tier: 'frontier', inputPerM: 1.75, outputPerM: 14, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.2-pro', aliases: [], tier: 'frontier', inputPerM: 21, outputPerM: 168, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-5.1', aliases: [], tier: 'frontier', inputPerM: 1.25, outputPerM: 10, status: 'deprecated', endsOn: '2027-04-01', replacement: 'gpt-6-sol', promo: null },
  {
    provider: 'openai',
    id: 'gpt-5',
    aliases: ['gpt-5-2025-08-07'],
    tier: 'frontier',
    inputPerM: 1.25,
    outputPerM: 10,
    status: 'deprecated',
    endsOn: '2026-12-11',
    replacement: 'gpt-5.6-sol',
    promo: null,
  },
  {
    provider: 'openai',
    id: 'gpt-5-mini',
    aliases: ['gpt-5-mini-2025-08-07'],
    tier: 'mid',
    inputPerM: 0.25,
    outputPerM: 2,
    status: 'deprecated',
    endsOn: '2026-12-11',
    replacement: 'gpt-5.6-terra',
    promo: null,
  },
  {
    provider: 'openai',
    id: 'gpt-5-nano',
    aliases: ['gpt-5-nano-2025-08-07'],
    tier: 'small',
    inputPerM: 0.05,
    outputPerM: 0.4,
    status: 'deprecated',
    endsOn: '2026-12-11',
    replacement: 'gpt-5.6-luna',
    promo: null,
  },
  {
    provider: 'openai',
    id: 'gpt-5-pro',
    aliases: ['gpt-5-pro-2025-10-06'],
    tier: 'frontier',
    inputPerM: 15,
    outputPerM: 120,
    status: 'deprecated',
    endsOn: '2026-12-11',
    replacement: 'gpt-5.6-sol',
    promo: null,
  },
  { provider: 'openai', id: 'gpt-4.1', aliases: ['gpt-4.1-2025-04-14'], tier: 'mid', inputPerM: 2, outputPerM: 8, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-4.1-mini', aliases: ['gpt-4.1-mini-2025-04-14'], tier: 'small', inputPerM: 0.4, outputPerM: 1.6, status: 'active', endsOn: null, replacement: null, promo: null },
  {
    provider: 'openai',
    id: 'gpt-4.1-nano',
    aliases: ['gpt-4.1-nano-2025-04-14'],
    tier: 'small',
    inputPerM: 0.1,
    outputPerM: 0.4,
    status: 'deprecated',
    endsOn: '2026-10-23',
    replacement: 'gpt-5.6-luna',
    promo: null,
  },
  {
    provider: 'openai',
    id: 'gpt-4o',
    aliases: ['gpt-4o-2024-08-06', 'gpt-4o-2024-11-20'],
    tier: 'mid',
    inputPerM: 2.5,
    outputPerM: 10,
    status: 'active',
    endsOn: null,
    replacement: null,
    promo: null,
  },
  { provider: 'openai', id: 'gpt-4o-2024-05-13', aliases: [], tier: 'mid', inputPerM: 5, outputPerM: 15, status: 'deprecated', endsOn: '2026-10-23', replacement: 'gpt-5.6-sol', promo: null },
  { provider: 'openai', id: 'gpt-4o-mini', aliases: ['gpt-4o-mini-2024-07-18'], tier: 'small', inputPerM: 0.15, outputPerM: 0.6, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'openai', id: 'o3', aliases: ['o3-2025-04-16'], tier: 'frontier', inputPerM: 2, outputPerM: 8, status: 'deprecated', endsOn: '2026-12-11', replacement: 'gpt-5.6-sol', promo: null },
  {
    provider: 'openai',
    id: 'o3-pro',
    aliases: ['o3-pro-2025-06-10'],
    tier: 'frontier',
    inputPerM: 20,
    outputPerM: 80,
    status: 'deprecated',
    endsOn: '2026-12-11',
    replacement: 'gpt-5.6-sol',
    promo: null,
  },
  {
    provider: 'openai',
    id: 'o4-mini',
    aliases: ['o4-mini-2025-04-16'],
    tier: 'mid',
    inputPerM: 1.1,
    outputPerM: 4.4,
    status: 'deprecated',
    endsOn: '2026-10-23',
    replacement: 'gpt-5.6-terra',
    promo: null,
  },
  {
    provider: 'openai',
    id: 'o3-mini',
    aliases: ['o3-mini-2025-01-31'],
    tier: 'mid',
    inputPerM: 1.1,
    outputPerM: 4.4,
    status: 'deprecated',
    endsOn: '2026-10-23',
    replacement: 'gpt-5.6-sol',
    promo: null,
  },
  { provider: 'openai', id: 'o1', aliases: ['o1-2024-12-17'], tier: 'frontier', inputPerM: 15, outputPerM: 60, status: 'deprecated', endsOn: '2026-10-23', replacement: 'gpt-5.6-sol', promo: null },
  {
    provider: 'openai',
    id: 'o1-pro',
    aliases: ['o1-pro-2025-03-19'],
    tier: 'frontier',
    inputPerM: 150,
    outputPerM: 600,
    status: 'deprecated',
    endsOn: '2026-10-23',
    replacement: 'gpt-5.6-sol',
    promo: null,
  },
  {
    provider: 'openai',
    id: 'gpt-4-turbo',
    aliases: ['gpt-4-turbo-2024-04-09'],
    tier: 'frontier',
    inputPerM: 10,
    outputPerM: 30,
    status: 'deprecated',
    endsOn: '2026-10-23',
    replacement: 'gpt-5.6-sol',
    promo: null,
  },
  { provider: 'openai', id: 'gpt-4-0613', aliases: ['gpt-4'], tier: 'frontier', inputPerM: 30, outputPerM: 60, status: 'deprecated', endsOn: '2026-10-23', replacement: 'gpt-5.6-sol', promo: null },
  {
    provider: 'openai',
    id: 'gpt-3.5-turbo',
    aliases: ['gpt-3.5-turbo-0125'],
    tier: 'small',
    inputPerM: 0.5,
    outputPerM: 1.5,
    status: 'deprecated',
    endsOn: '2026-10-23',
    replacement: 'gpt-5.6-terra',
    promo: null,
  },
  { provider: 'openai', id: 'gpt-3.5-turbo-1106', aliases: [], tier: 'small', inputPerM: 1, outputPerM: 2, status: 'retired', endsOn: '2026-09-28', replacement: null, promo: null },
  { provider: 'openai', id: 'gpt-3.5-turbo-instruct', aliases: [], tier: 'small', inputPerM: 1.5, outputPerM: 2, status: 'retired', endsOn: '2026-09-28', replacement: null, promo: null },
  { provider: 'openai', id: 'chat-latest', aliases: [], tier: 'frontier', inputPerM: 5, outputPerM: 30, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-fable-5-1', aliases: [], tier: 'frontier', inputPerM: 10, outputPerM: 50, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-mythos-5-1', aliases: [], tier: 'frontier', inputPerM: 10, outputPerM: 50, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-fable-5', aliases: [], tier: 'frontier', inputPerM: 10, outputPerM: 50, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-mythos-5', aliases: [], tier: 'frontier', inputPerM: 10, outputPerM: 50, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-opus-5-5', aliases: [], tier: 'frontier', inputPerM: 4, outputPerM: 20, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-opus-5', aliases: [], tier: 'frontier', inputPerM: 5, outputPerM: 25, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-opus-4-8', aliases: [], tier: 'frontier', inputPerM: 5, outputPerM: 25, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-opus-4-7', aliases: [], tier: 'frontier', inputPerM: 5, outputPerM: 25, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-opus-4-6', aliases: [], tier: 'frontier', inputPerM: 5, outputPerM: 25, status: 'active', endsOn: null, replacement: null, promo: null },
  {
    provider: 'anthropic',
    id: 'claude-opus-4-5-20251101',
    aliases: ['claude-opus-4-5'],
    tier: 'frontier',
    inputPerM: 5,
    outputPerM: 25,
    status: 'active',
    endsOn: null,
    replacement: null,
    promo: null,
  },
  {
    provider: 'anthropic',
    id: 'claude-opus-4-1-20250805',
    aliases: ['claude-opus-4-1'],
    tier: 'frontier',
    inputPerM: 15,
    outputPerM: 75,
    status: 'retired',
    endsOn: '2026-08-05',
    replacement: null,
    promo: null,
  },
  {
    provider: 'anthropic',
    id: 'claude-opus-4-20250514',
    aliases: ['claude-opus-4-0'],
    tier: 'frontier',
    inputPerM: 15,
    outputPerM: 75,
    status: 'retired',
    endsOn: '2026-06-15',
    replacement: null,
    promo: null,
  },
  { provider: 'anthropic', id: 'claude-sonnet-5-5', aliases: [], tier: 'mid', inputPerM: 2, outputPerM: 10, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-sonnet-5', aliases: [], tier: 'mid', inputPerM: 2, outputPerM: 10, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-sonnet-4-6', aliases: [], tier: 'mid', inputPerM: 3, outputPerM: 15, status: 'active', endsOn: null, replacement: null, promo: null },
  {
    provider: 'anthropic',
    id: 'claude-sonnet-4-5-20250929',
    aliases: ['claude-sonnet-4-5'],
    tier: 'mid',
    inputPerM: 3,
    outputPerM: 15,
    status: 'deprecated',
    endsOn: '2026-11-30',
    replacement: null,
    promo: null,
  },
  {
    provider: 'anthropic',
    id: 'claude-sonnet-4-20250514',
    aliases: ['claude-sonnet-4-0'],
    tier: 'mid',
    inputPerM: 3,
    outputPerM: 15,
    status: 'retired',
    endsOn: '2026-06-15',
    replacement: null,
    promo: null,
  },
  { provider: 'anthropic', id: 'claude-3-7-sonnet-20250219', aliases: [], tier: 'mid', inputPerM: null, outputPerM: null, status: 'retired', endsOn: '2026-02-19', replacement: null, promo: null },
  { provider: 'anthropic', id: 'claude-haiku-4-5-20251001', aliases: ['claude-haiku-4-5'], tier: 'small', inputPerM: 1, outputPerM: 5, status: 'active', endsOn: null, replacement: null, promo: null },
  {
    provider: 'anthropic',
    id: 'claude-3-5-haiku-20241022',
    aliases: ['claude-3-5-haiku-latest'],
    tier: 'small',
    inputPerM: 0.8,
    outputPerM: 4,
    status: 'retired',
    endsOn: '2026-02-19',
    replacement: null,
    promo: null,
  },
  { provider: 'anthropic', id: 'claude-3-haiku-20240307', aliases: [], tier: 'small', inputPerM: null, outputPerM: null, status: 'retired', endsOn: '2026-04-20', replacement: null, promo: null },
  {
    provider: 'google',
    id: 'gemini-3.1-pro-preview',
    aliases: ['gemini-3.1-pro-preview-customtools'],
    tier: 'frontier',
    inputPerM: 2,
    outputPerM: 12,
    status: 'active',
    endsOn: null,
    replacement: null,
    promo: null,
  },
  {
    provider: 'google',
    id: 'gemini-3.8-flash',
    aliases: [],
    tier: 'mid',
    inputPerM: 0.75,
    outputPerM: 3.75,
    status: 'active',
    endsOn: null,
    replacement: null,
    promo: { until: '2026-12-31', inputPerM: 1.5, outputPerM: 7.5 },
  },
  {
    provider: 'google',
    id: 'gemini-3.7-flash',
    aliases: [],
    tier: 'mid',
    inputPerM: 0.75,
    outputPerM: 3.75,
    status: 'active',
    endsOn: null,
    replacement: null,
    promo: { until: '2026-12-31', inputPerM: 1.5, outputPerM: 7.5 },
  },
  {
    provider: 'google',
    id: 'gemini-3.6-flash',
    aliases: [],
    tier: 'mid',
    inputPerM: 0.75,
    outputPerM: 3.75,
    status: 'active',
    endsOn: null,
    replacement: null,
    promo: { until: '2026-12-31', inputPerM: 1.5, outputPerM: 7.5 },
  },
  { provider: 'google', id: 'gemini-3.5-flash', aliases: [], tier: 'mid', inputPerM: 1.5, outputPerM: 9, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'google', id: 'gemini-3.5-flash-lite', aliases: [], tier: 'small', inputPerM: 0.3, outputPerM: 2.5, status: 'active', endsOn: null, replacement: null, promo: null },
  {
    provider: 'google',
    id: 'gemini-3.1-flash-lite',
    aliases: [],
    tier: 'small',
    inputPerM: 0.25,
    outputPerM: 1.5,
    status: 'deprecated',
    endsOn: '2027-05-07',
    replacement: 'gemini-3.5-flash-lite',
    promo: null,
  },
  { provider: 'google', id: 'gemini-3-flash-preview', aliases: [], tier: 'mid', inputPerM: 0.5, outputPerM: 3, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'google', id: 'gemini-2.5-pro', aliases: [], tier: 'frontier', inputPerM: 1.25, outputPerM: 10, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'google', id: 'gemini-2.5-flash', aliases: [], tier: 'mid', inputPerM: 0.3, outputPerM: 2.5, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'google', id: 'gemini-2.5-flash-lite', aliases: [], tier: 'small', inputPerM: 0.1, outputPerM: 0.4, status: 'active', endsOn: null, replacement: null, promo: null },
  {
    provider: 'google',
    id: 'gemini-3-pro-preview',
    aliases: [],
    tier: 'frontier',
    inputPerM: null,
    outputPerM: null,
    status: 'retired',
    endsOn: '2026-03-09',
    replacement: 'gemini-3.1-pro-preview',
    promo: null,
  },
  {
    provider: 'google',
    id: 'gemini-2.0-flash',
    aliases: ['gemini-2.0-flash-001'],
    tier: 'small',
    inputPerM: null,
    outputPerM: null,
    status: 'retired',
    endsOn: '2026-06-01',
    replacement: 'gemini-3.6-flash',
    promo: null,
  },
  {
    provider: 'google',
    id: 'gemini-2.0-flash-lite',
    aliases: ['gemini-2.0-flash-lite-001'],
    tier: 'small',
    inputPerM: null,
    outputPerM: null,
    status: 'retired',
    endsOn: '2026-06-01',
    replacement: 'gemini-3.1-flash-lite',
    promo: null,
  },
  {
    provider: 'mistral',
    id: 'mistral-medium-3-5',
    aliases: ['mistral-medium-latest', 'mistral-medium-3'],
    tier: 'frontier',
    inputPerM: 1.5,
    outputPerM: 7.5,
    status: 'active',
    endsOn: null,
    replacement: null,
    promo: null,
  },
  { provider: 'mistral', id: 'mistral-large-2512', aliases: ['mistral-large-latest'], tier: 'mid', inputPerM: 0.5, outputPerM: 1.5, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'mistral', id: 'mistral-small-2603', aliases: ['mistral-small-latest'], tier: 'small', inputPerM: 0.15, outputPerM: 0.6, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'mistral', id: 'ministral-14b-2512', aliases: ['ministral-14b-latest'], tier: 'small', inputPerM: 0.2, outputPerM: 0.2, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'mistral', id: 'ministral-8b-2512', aliases: ['ministral-8b-latest'], tier: 'small', inputPerM: 0.15, outputPerM: 0.15, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'mistral', id: 'ministral-3b-2512', aliases: ['ministral-3b-latest'], tier: 'small', inputPerM: 0.1, outputPerM: 0.1, status: 'active', endsOn: null, replacement: null, promo: null },
  { provider: 'mistral', id: 'codestral-2508', aliases: ['codestral-latest'], tier: 'small', inputPerM: 0.3, outputPerM: 0.9, status: 'active', endsOn: null, replacement: null, promo: null },
  {
    provider: 'mistral',
    id: 'mistral-medium-2508',
    aliases: [],
    tier: 'mid',
    inputPerM: null,
    outputPerM: null,
    status: 'retired',
    endsOn: '2026-08-31',
    replacement: 'mistral-medium-3-5',
    promo: null,
  },
  { provider: 'mistral', id: 'mistral-medium-2505', aliases: [], tier: 'mid', inputPerM: null, outputPerM: null, status: 'retired', endsOn: '2026-08-31', replacement: null, promo: null },
  {
    provider: 'mistral',
    id: 'mistral-small-2506',
    aliases: [],
    tier: 'small',
    inputPerM: null,
    outputPerM: null,
    status: 'retired',
    endsOn: '2026-07-31',
    replacement: 'mistral-small-2603',
    promo: null,
  },
  {
    provider: 'mistral',
    id: 'mistral-large-2411',
    aliases: [],
    tier: 'frontier',
    inputPerM: null,
    outputPerM: null,
    status: 'retired',
    endsOn: '2026-05-31',
    replacement: 'mistral-medium-3-5',
    promo: null,
  },
  {
    provider: 'mistral',
    id: 'open-mistral-nemo-2407',
    aliases: [],
    tier: 'small',
    inputPerM: null,
    outputPerM: null,
    status: 'retired',
    endsOn: '2026-07-31',
    replacement: 'ministral-8b-2512',
    promo: null,
  },
];

/** Switches worth suggesting, each with the reason in plain words. The provider's own replacement for a retiring model is added automatically. */
export const SWITCHES: { from: string; to: string; reason: string }[] = [
  {
    from: 'gpt-6-astra',
    to: 'gpt-6.1-sol',
    reason: 'Same GPT-6 family, mid tier; 5x cheaper input and output.',
  },
  {
    from: 'gpt-6.1-sol',
    to: 'gpt-6-luna',
    reason: 'Same family, smallest model; suited to short routine requests such as classification and extraction.',
  },
  {
    from: 'gpt-5.5',
    to: 'gpt-6.1-sol',
    reason: 'Newer generation at lower list price ($2/$10 vs $5/$30).',
  },
  {
    from: 'gpt-4o',
    to: 'gpt-6-luna',
    reason: 'Current small model priced well below gpt-4o; test for routine chat and summarisation.',
  },
  {
    from: 'o4-mini',
    to: 'gpt-5.6-terra',
    reason: 'o4-mini shuts down 2026-10-23; OpenAI names gpt-5.6-terra as substitute.',
  },
  {
    from: 'claude-opus-5-5',
    to: 'claude-sonnet-5-5',
    reason: 'Same generation, mid tier; half the input and output price.',
  },
  {
    from: 'claude-sonnet-5-5',
    to: 'claude-haiku-4-5-20251001',
    reason: 'Smallest current Claude; half the price, suited to short routine requests.',
  },
  {
    from: 'claude-opus-4-1-20250805',
    to: 'claude-opus-5-5',
    reason: 'Retired model; current Opus is cheaper ($4/$20 vs $15/$75).',
  },
  {
    from: 'claude-sonnet-4-5-20250929',
    to: 'claude-sonnet-5-5',
    reason: 'Deprecated, retires 2026-11-30; successor is cheaper ($2/$10 vs $3/$15).',
  },
  {
    from: 'gemini-3.1-pro-preview',
    to: 'gemini-3.8-flash',
    reason: "Same provider's newest Flash; lower price (promotional through 2026-12-31).",
  },
  {
    from: 'gemini-3.8-flash',
    to: 'gemini-3.5-flash-lite',
    reason: 'Flash-Lite tier, optimised for high-volume simple tasks.',
  },
  {
    from: 'gemini-3.5-flash',
    to: 'gemini-3.8-flash',
    reason: 'Newer Flash is cheaper than 3.5 Flash both before and after the 2027 price change.',
  },
  {
    from: 'mistral-medium-3-5',
    to: 'mistral-small-2603',
    reason: 'Same provider, small tier; 10x cheaper input, suited to routine requests.',
  },
  {
    from: 'mistral-medium-3-5',
    to: 'mistral-large-2512',
    reason: 'Older open-weight Large 3 is priced below Medium 3.5.',
  },
  {
    from: 'gpt-4.1',
    to: 'gpt-4.1-mini',
    reason: 'Same family, smaller; 5x cheaper, suited to short routine requests.',
  },
];
